### ISSUE TITLE
script works for a few seconds and then doesn't

### ISSUE THREAD

**Issue by dsusco** [deanmcniven/wsl2-vpn-support#3]
Has anyone else encountered this? I start up my WSL (Debian), connect to the VPN, and can SSH from WSL for a few seconds, then get a "name or service not known". Ideas?

I should add, connecting via IP works no problem.

**Comment by deanmcniven** [comment]
This script will configure the network routes for the WSL instance, but you may need to configure the `/etc/resolv.conf` file to get name resolution working correctly in your environment

One test to confirm/deny is to attempt to curl/telnet etc to a fixed IP address, if that works its a name resolution issue, otherwise its likely routing (that this script attempts to fix)
